### ISSUE TITLE
Autolaunch error: X11 initialization failed error occurs when run as a cronjob

### ISSUE THREAD

**Issue by hussaintamboli** [hussaintamboli/informant#1]
Cron:
0 \* \* \* \* svn.py 2> /home/hussain/tmp/svn.log

I found below error in svn.log

$ cat svn.log 

```
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
warnings.warn(str(e), _gtk.Warning)
** (svn.py:30689): WARNING **: Command line `dbus-launch --    autolaunch=b569e3e515ab65bef50c2d3000000008 --binary-syntax --close-stderr' exited with non-zero     exit status 1: Autolaunch error: X11 initialization failed.\n
Traceback (most recent call last):
 File "/home/hussain/Documents/MyRepos/informant/svn.py", line 98, in <module>
 hist.list_status_working_copy()
 File "/home/hussain/Documents/MyRepos/informant/svn.py", line 87, in list_status_working_copy
 raise errors.SvnError(e)
 errors.SvnError: Error in showing notification. Command line `dbus-launch -- autolaunch=b569e3e515ab65bef50c2d3000000008 --binary-syntax --close-stderr' exited with non-zero   exit status 1: Autolaunch error: X11 initialization failed.\n
```

**Comment by hussaintamboli** [comment]
## Fix

Added `DISPLAY=:0.0` in the cron expression

0 \* \* \* \* DISPLAY=:0.0 svn.py 2> /home/hussain/tmp/svn.log
0 \* \* \* \* DISPLAY=:0.0 gitt.py 2> /home/hussain/tmp/git.log

## References
- [ gsettings with cron ](http://stackoverflow.com/questions/10374520/gsettings-with-cron#comment44885451_10374520)
- [ Crontab doesn't run script correctly ](http://ubuntuforums.org/showthread.php?t=1023215)
